# Generated by Django 4.0.4 on 2022-06-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='organization',
        ),
    ]
