# Generated by Django 4.0.4 on 2022-06-19 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_volunteerrequest_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizacionOferente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteerrequest',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SesionSolicitada', to='database.session'),
        ),
        migrations.AlterField(
            model_name='volunteerrequest',
            name='volunteer',
            field=models.ManyToManyField(null=True, related_name='Solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
