# Generated by Django 4.0.4 on 2022-06-19 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_volunteerrequest_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrequest',
            name='volunteer',
            field=models.ManyToManyField(related_name='Solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
