# Generated by Django 4.0.4 on 2022-06-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_volunteerrequest_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
