# Generated by Django 4.0.4 on 2022-04-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='category',
        ),
        migrations.RemoveField(
            model_name='session',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='session',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='session',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Turn',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
